### ISSUE TITLE
More Example For Drawer - v4

### ISSUE THREAD

**Issue by Steam1996** [bootstrap-styled/bootstrap-styled#119] opened 2019-11-19 16:00 UTC
Hi,

Is it possible to provide more examples of [Drawer](https://bootstrap-styled.github.io/v4/#/UI%20Components/Components/Drawer)?  I would like to implement a similar thing as [the official page](https://bootstrap-styled.github.io/v4/) has. I inspected it and it actually is a Sidebar. Is it implemented with `<Drawer />` as well?

**Comment by kopax** [comment] 2019-11-19 16:56
All the source code is open source. If you can't find source in the repository, perhaps you are looking for :  

- http://github.com/bootstrap-styled/rsg-components => bootstrap-version of components used to build react-styleguidist documentation with bootstrap-styled
- http://github.com/bootstrap-styled/documentation => a theme configuration extension we use for our all our main documentation

It's possible that we have saved the navigation in http://github.com/bootstrap-styled/navigation

/cc @santaclauze

**Comment by Steam1996** [comment] 2019-11-19 20:29
Thank for the comment but I couldn't use `rsg-components`. I kept getting a lot of errors and I ended up installing lots of dependencies and the last error I got was `aws-sdk` dependency from `@rollup-umd/documentation`.

**Comment by kopax** [comment] 2019-11-20 09:28
At first, why do you wanted to use `rsg-components`? Are you building a documentation with react-styleguidist? If yes, then you have an example of configuration in `@rollup-umd/documentation`, this is where we override rsg-components with @bootstrap-styled/rsg-components. Keep in mind that we support react-styleguidist@9.1.4, to update, we need to update @bootstrap-styled/rsg-components for react-styleguidist@10.x. Contributors are welcome.

> the last error I got was missing aws-sdk dependency from @rollup-umd/documentation.

Please describe what you want, and precise why are you performing those action. I have no clue of what you are doing, no clue of what is that error, no reproduction... so I can't really help you the way you ask.

**Comment by kopax** [comment] 2020-04-09 09:35
I am closing this since no reply, if you feel this is unresolved or should get additional attention, feel free to reply.

**Closed by kopax** 2020-04-09 09:35 UTC
Labels: question
